name: Run BAT PS JS Scripts

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: dir

      - name: Run BAT
        shell: cmd
        run: run_OBHPS.bat

      - name: Run PowerShell
        run: powershell -ExecutionPolicy Bypass -File run_all_tests_OBHPS.ps1

      - name: Install Node dependencies
        run: npm install

      - name: Run JavaScript
        run: node coms.spec.js
