name: Run BAT PS JS Scripts

on:
  push:
    branches: [ "main" ]

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run BAT
        run: scripts\run_OBHPS.bat

      - name: Run PowerShell
        shell: powershell
        run: scripts\run_all_tests_OBHPS.ps1

      - name: Run JavaScript
        run: node scripts\coms.spec.js
